#template: Hello, %s!

#defaultName: ${DW_DEFAULT_NAME:-Stranger}

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.cj.jdbc.Driver
    # the username
    user: osmar
    # the password
    password: mysql
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://127.0.0.1/chikitania?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

logging:
  level: INFO
  loggers:
    com.users.app: DEBUG
    
mongoHost : localhost
mongoPort : 27017
mongoDB : kardex
collectionName: kardex

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
      port: 5000
      type: http
      
clientSite: http://127.0.0.1:5000
